"""create todo table

Revision ID: b24f4dc83080
Revises: 
Create Date: 2024-05-05 00:16:16.061211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24f4dc83080'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Event',
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('festival_description', sa.String(), nullable=True),
    sa.Column('festival_img', sa.String(), nullable=True),
    sa.Column('festival_data', sa.DateTime(), nullable=True),
    sa.Column('festival_address', sa.String(), nullable=True),
    sa.Column('festival_end_time', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('festival_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Event')
    # ### end Alembic commands ###
